version: '3'
services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - api_network
    expose:
      - "${DB_PORT}"
    restart: on-failure

  app:
    build: ./app
    container_name: app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    ports:
      - "${APP_PORT}:${APP_PORT}"
    entrypoint: [ "bash", "./entrypoint.sh" ]
    restart: on-failure

networks:
  api_network:
    driver: bridge
      
volumes:
  postgres_data: